# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kompass < Formula
  desc "Kubernetes resource relationship visualizer"
  homepage "https://github.com/karloie/kompass"
  version "0.0.13"
  license "MIT"

  on_macos do
    url "https://github.com/karloie/kompass/releases/download/v0.0.13/kompass_0.0.13_darwin_all.tar.gz"
    sha256 "9c52c25cb7fd83ff1b8595b521aa172edd205929fab331201b612b394885fa4e"

    define_method(:install) do
      bin.install "kompass"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/karloie/kompass/releases/download/v0.0.13/kompass_0.0.13_linux_amd64.tar.gz"
      sha256 "5db618a38798862efa603eb48ff14c23342dd2a33dc101a9797a35752f38bb96"
      define_method(:install) do
        bin.install "kompass"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/karloie/kompass/releases/download/v0.0.13/kompass_0.0.13_linux_arm64.tar.gz"
      sha256 "afc1f78f3c69e3cbf381d0577a22d8822a67b015dcfbf254c956088aeaba9889"
      define_method(:install) do
        bin.install "kompass"
      end
    end
  end
end
