# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kompass < Formula
  desc "Kubernetes resource relationship visualizer"
  homepage "https://github.com/karloie/kompass"
  version "0.0.5"
  license "MIT"

  on_macos do
    url "https://github.com/karloie/kompass/releases/download/v0.0.5/kompass_0.0.5_darwin_all.tar.gz"
    sha256 "c12d4f56338f32938cbcd53ba8cc2f866494668f4e7d8a061588aa93cebd3616"

    define_method(:install) do
      bin.install "kompass"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/karloie/kompass/releases/download/v0.0.5/kompass_0.0.5_linux_amd64.tar.gz"
      sha256 "4d0228afc1a3491c991bdb97fa33bf417cc5c1480b02f9236cb1c3987844dd88"
      define_method(:install) do
        bin.install "kompass"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/karloie/kompass/releases/download/v0.0.5/kompass_0.0.5_linux_arm64.tar.gz"
      sha256 "7994b18aa3207995a4a77d142985650adfe842ab366005de9ffb8cc5f0547217"
      define_method(:install) do
        bin.install "kompass"
      end
    end
  end
end
