# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kompass < Formula
  desc "Kubernetes resource relationship visualizer"
  homepage "https://github.com/karloie/kompass"
  version "0.0.15"
  license "MIT"

  on_macos do
    url "https://github.com/karloie/kompass/releases/download/v0.0.15/kompass_0.0.15_darwin_all.tar.gz"
    sha256 "3ccb9fde2da5e096b15e72d7f597d795499f8eb3e1ad06d1e7cbeafd0ade17ca"

    define_method(:install) do
      bin.install "kompass"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/karloie/kompass/releases/download/v0.0.15/kompass_0.0.15_linux_amd64.tar.gz"
      sha256 "9ecf669b4a5fe5ea8c186d000f3cd3ea2b94b08634cc79282f6a2641e824a2ab"
      define_method(:install) do
        bin.install "kompass"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/karloie/kompass/releases/download/v0.0.15/kompass_0.0.15_linux_arm64.tar.gz"
      sha256 "cb41e80f1439e115d9422b5994fffd5234d084a8737c8e294a1dba3707c5b04a"
      define_method(:install) do
        bin.install "kompass"
      end
    end
  end
end
