# This file was generated by GoReleaser. DO NOT EDIT.
cask "bastille" do
  name "bastille"
  desc "Application built with Go"
  homepage "https://github.com/karloie/bastille"
  version "0.0.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bastille"

  on_macos do
    url "https://github.com/karloie/bastille/releases/download/v#{version}/bastille_#{version}_darwin_all.tar.gz"
    sha256 "186332cd765c4e1f122673bf74ce23811deecb86ac7f5cd16902cb2299323b05"
  end

  on_linux do
    on_intel do
      url "https://github.com/karloie/bastille/releases/download/v#{version}/bastille_#{version}_linux_amd64.tar.gz"
      sha256 "322127f773877d13c7227c717a6413618c80cf62caf04d6e556b216b2e669ee7"
    end
    on_arm do
      url "https://github.com/karloie/bastille/releases/download/v#{version}/bastille_#{version}_linux_arm64.tar.gz"
      sha256 "716189a0d23dc986c9ef50ece74049ab442c58d29ed731c9a98185ba39148bd7"
    end
  end

  # No zap stanza required
end
