# This file was generated by GoReleaser. DO NOT EDIT.
cask "bastille" do
  name "bastille"
  desc "Application built with Go"
  homepage "https://github.com/karloie/bastille"
  version "0.0.11"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bastille"

  on_macos do
    url "https://github.com/karloie/bastille/releases/download/v#{version}/bastille_#{version}_darwin_all.tar.gz"
    sha256 "4ba94615f6e3676dd515f3b49c015be164189107110c3bb576195caf935a05df"
  end

  on_linux do
    on_intel do
      url "https://github.com/karloie/bastille/releases/download/v#{version}/bastille_#{version}_linux_amd64.tar.gz"
      sha256 "41abc6a87d557e60d9af98113e3b3e8d39556016dca512a870248d89d4a5fed5"
    end
    on_arm do
      url "https://github.com/karloie/bastille/releases/download/v#{version}/bastille_#{version}_linux_arm64.tar.gz"
      sha256 "5aba4cf7135bfa31e0a76fbd8efae778ff9b859184faa97cefaad37ca89f9150"
    end
  end

  # No zap stanza required
end
