# This file was generated by GoReleaser. DO NOT EDIT.
cask "kompass" do
  name "kompass"
  desc "Application built with Go"
  homepage "https://github.com/karloie/kompass"
  version "0.0.16"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kompass"

  on_macos do
    url "https://github.com/karloie/kompass/releases/download/v#{version}/kompass_#{version}_darwin_all.tar.gz"
    sha256 "4d4c58a5955dd761b2cd8419eeb173573fa12fc186fd2b43f1d016140675d915"
  end

  on_linux do
    on_intel do
      url "https://github.com/karloie/kompass/releases/download/v#{version}/kompass_#{version}_linux_amd64.tar.gz"
      sha256 "8d83607069d8c278b5cc675bf5fb4f04d7dac8c7f3450ffaad7d1600612ddea8"
    end
    on_arm do
      url "https://github.com/karloie/kompass/releases/download/v#{version}/kompass_#{version}_linux_arm64.tar.gz"
      sha256 "874e543d545ea9e988f9973c4f3d865b83ce7d84b8025d8adf5613c4da50746a"
    end
  end

  # No zap stanza required
end
