# This file was generated by GoReleaser. DO NOT EDIT.
cask "kompass" do
  name "kompass"
  desc "Application built with Go"
  homepage "https://github.com/karloie/kompass"
  version "0.0.22"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kompass"

  on_macos do
    url "https://github.com/karloie/kompass/releases/download/v#{version}/kompass_#{version}_darwin_all.tar.gz"
    sha256 "e005cb4b86f5ad4adbe4b976e8bd4ff07fa36b8d868de1502f8e85213faac7fd"
  end

  on_linux do
    on_intel do
      url "https://github.com/karloie/kompass/releases/download/v#{version}/kompass_#{version}_linux_amd64.tar.gz"
      sha256 "5a967d59c51ac50acd7fb013df37ad8aea504f254a113d3924780ecd5f2aa3dd"
    end
    on_arm do
      url "https://github.com/karloie/kompass/releases/download/v#{version}/kompass_#{version}_linux_arm64.tar.gz"
      sha256 "e774cb1c6dedd9665117d3c1be370d60748567ad13d479c0fa10da9809b1d5cc"
    end
  end

  # No zap stanza required
end
