# This file was generated by GoReleaser. DO NOT EDIT.
cask "kompass" do
  name "kompass"
  desc "Application built with Go"
  homepage "https://github.com/karloie/kompass"
  version "0.0.19"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kompass"

  on_macos do
    url "https://github.com/karloie/kompass/releases/download/v#{version}/kompass_#{version}_darwin_all.tar.gz"
    sha256 "f8c40a6c31f9dfb75b0439e6dde69d81611dee414891982c443411ebf50b7b8a"
  end

  on_linux do
    on_intel do
      url "https://github.com/karloie/kompass/releases/download/v#{version}/kompass_#{version}_linux_amd64.tar.gz"
      sha256 "89486af06d813c7ac1b24d5a5a370203faf56aa569360d1dd49de96cf84e4997"
    end
    on_arm do
      url "https://github.com/karloie/kompass/releases/download/v#{version}/kompass_#{version}_linux_arm64.tar.gz"
      sha256 "bfc15d57b9751243e8e223ce3e8a687d3cc2b63ad7193c127664d09ca26be3b3"
    end
  end

  # No zap stanza required
end
