# This file was generated by GoReleaser. DO NOT EDIT.
cask "shipkit" do
  name "shipkit"
  desc "Make-first release automation tool"
  homepage "https://github.com/karloie/shipkit"
  version "0.0.75"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shipkit"

  on_macos do
    url "https://github.com/karloie/shipkit/releases/download/v#{version}/shipkit_#{version}_darwin_all.tar.gz"
    sha256 "605e7a9bf0c35fd004c0d060ae2cc5131381cdfdb63eccafde4e6eda00bba3f5"
  end

  on_linux do
    on_intel do
      url "https://github.com/karloie/shipkit/releases/download/v#{version}/shipkit_#{version}_linux_amd64.tar.gz"
      sha256 "ef4426af2235cbfc969e3c27289fa24ece3fcf24738389dd5942d0543e69cc06"
    end
    on_arm do
      url "https://github.com/karloie/shipkit/releases/download/v#{version}/shipkit_#{version}_linux_arm64.tar.gz"
      sha256 "bf6b7ae8bd1287e69a3c8aab0d79f0c9b56c19ab9a7de3c95450a65cf9e67d6d"
    end
  end

  # No zap stanza required
end
