# This file was generated by GoReleaser. DO NOT EDIT.
cask "shipkit" do
  name "shipkit"
  desc "Application built with Go"
  homepage "https://github.com/karloie/shipkit"
  version "0.0.30"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shipkit"

  on_macos do
    url "https://github.com/karloie/shipkit/releases/download/v#{version}/shipkit_#{version}_darwin_all.tar.gz"
    sha256 "90e6bf20fdef147a2fb0fa63d57536c99a49b1147e7fc15ff7ef41cfe6c87e8f"
  end

  on_linux do
    on_intel do
      url "https://github.com/karloie/shipkit/releases/download/v#{version}/shipkit_#{version}_linux_amd64.tar.gz"
      sha256 "a2e107219b994a7d4e8782a9456f19a0c1de18a6edcef4364f403848bf1a74d2"
    end
    on_arm do
      url "https://github.com/karloie/shipkit/releases/download/v#{version}/shipkit_#{version}_linux_arm64.tar.gz"
      sha256 "768c1031877616b532b90e8d96b2659b62d102215c1b14715d17fa2138a607c9"
    end
  end

  # No zap stanza required
end
