# This file was generated by GoReleaser. DO NOT EDIT.
cask "shipkit" do
  name "shipkit"
  desc "Application built with Go"
  homepage "https://github.com/karloie/shipkit"
  version "0.3.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shipkit"

  on_macos do
    url "https://github.com/karloie/shipkit/releases/download/v#{version}/shipkit_#{version}_darwin_all.tar.gz"
    sha256 "1b92e2ddeba5fb99f701f9db3e131f2d7fbe92c781d02121f69ac12d48f61f39"
  end

  on_linux do
    on_intel do
      url "https://github.com/karloie/shipkit/releases/download/v#{version}/shipkit_#{version}_linux_amd64.tar.gz"
      sha256 "cf5de075425c35601b87a6a81103831626d40dd1ec25a34a90f8bb69fd9fde1b"
    end
    on_arm do
      url "https://github.com/karloie/shipkit/releases/download/v#{version}/shipkit_#{version}_linux_arm64.tar.gz"
      sha256 "70829c88dc2580a7383582e50a96cd869f660aba9595c469c48455ef8f6672f7"
    end
  end

  # No zap stanza required
end
