# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shipkit < Formula
  desc "Make-first release automation tool"
  homepage "https://github.com/karloie/shipkit"
  version "0.0.38"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/karloie/shipkit/releases/download/v0.0.38/shipkit_0.0.38_darwin_amd64.tar.gz"
      sha256 "f2d78ff1dc730919f4c8d4554ca3e180fb327957fb6dc428b469e6ff7d5a39e9"

      define_method(:install) do
        bin.install "shipkit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/karloie/shipkit/releases/download/v0.0.38/shipkit_0.0.38_darwin_arm64.tar.gz"
      sha256 "20af06281142273a360afdda2a7e79adb36cf960daa22d31c2c16797d092d934"

      define_method(:install) do
        bin.install "shipkit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/karloie/shipkit/releases/download/v0.0.38/shipkit_0.0.38_linux_amd64.tar.gz"
      sha256 "664372e21115cd4f083ae9b73216d03a70303c8573dd9f60881a3ae1ab1108e2"
      define_method(:install) do
        bin.install "shipkit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/karloie/shipkit/releases/download/v0.0.38/shipkit_0.0.38_linux_arm64.tar.gz"
      sha256 "decce4b64dd4dc47c7616c373f2c3c62078abafc11d1be7beb0511a0c0a28a95"
      define_method(:install) do
        bin.install "shipkit"
      end
    end
  end

  test do
    system "#{bin}/shipkit", "version"
  end
end
